name: Prueba ejecucion de script de JavaScript
run-name: ${{ github.actor }} esta probando la ejecucion de un script de JavaScript
on: [push]

jobs:
    ejecuta-js:
        runs-on: ubuntu-latest
        steps:
            - run: echo "inicia actions"
            - run: node --version
            - name: Check out repository code
              uses: actions/checkout@v6
            - run: ls -al
            - run: node app.js